name: CI
on:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: usafder/setup-node-with-cache@v1.0.0
        with:
          NODE_VERSION: 18.14.2
